name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:humble-desktop
      options: --user root
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y \
          build-essential \
          cmake \
          git \
          pkg-config \
          python3-colcon-common-extensions

    - name: Build and test
      run: |
        # Install Quill library
        git clone https://github.com/odygrd/quill.git
        cd quill
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j$(nproc)
        make install
        ldconfig
        cd ../..
        
        # Debug: Check if Quill is installed
        echo "Checking Quill installation..."
        ls -la /usr/local/include/ | grep quill || echo "Quill not found in /usr/local/include"
        find /usr -name "LogMacros.h" 2>/dev/null | head -5 || echo "LogMacros.h not found"
        
        # Build and test package
        . /opt/ros/humble/setup.sh
        colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON
        . install/setup.sh
        colcon test --event-handlers console_direct+
        colcon test-result --all 