name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:humble-desktop
      options: --user root
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y \
          build-essential \
          cmake \
          git \
          pkg-config \
          python3-colcon-common-extensions

    - name: Install Quill library
      run: |
        # Clone and build Quill from source
        git clone https://github.com/odygrd/quill.git
        cd quill
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j$(nproc)
        make install
        ldconfig

    - name: Build package
      run: |
        . /opt/ros/humble/setup.sh
        colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release

    - name: Run tests
      run: |
        . /opt/ros/humble/setup.sh
        . install/setup.sh
        colcon test --event-handlers console_direct+

    - name: Check test results
      run: |
        . /opt/ros/humble/setup.sh
        . install/setup.sh
        colcon test-result --all 