name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    needs: build-deb
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup ROS2 Humble
      uses: ros-tooling/setup-ros@v0.5.0
      with:
        required-ros-distributions: humble

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libquill-dev \
          devscripts \
          debhelper \
          dh-make \
          git \
          pkg-config

    - name: Build Debian package
      run: |
        chmod +x scripts/build_deb.sh
        ./scripts/build_deb.sh

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## What's Changed
          
          ### Features
          - High-performance ROS2 logging system using Quill library
          - Realtime-optimized backend thread configuration
          - Comprehensive unit tests and performance benchmarks
          - Debian package support
          
          ### Installation
          ```bash
          # From source
          git clone https://github.com/ruslan98m/ros2_quill_logger.git
          cd ros2_quill_logger
          mkdir build && cd build
          cmake .. && make
          sudo make install
          
          # From Debian package
          sudo dpkg -i quill-logger_*.deb
          sudo apt-get install -f
          ```
          
          ### Usage
          ```cpp
          #include <quill_logger/quill_logger.hpp>
          
          int main() {
              quill_logger::QuillLogger::initialize();
              auto logger = quill_logger::QuillLogger::getLogger("my_node");
              logger->info("Hello from quill_logger!");
              return 0;
          }
          ```
        draft: false
        prerelease: false

    - name: Upload Debian package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ../quill-logger_*.deb
        asset_name: quill-logger.deb
        asset_content_type: application/vnd.debian.binary-package

  build-deb:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup ROS2 Humble
      uses: ros-tooling/setup-ros@v0.5.0
      with:
        required-ros-distributions: humble

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libquill-dev \
          devscripts \
          debhelper \
          dh-make \
          git \
          pkg-config

    - name: Build Debian package
      run: |
        chmod +x scripts/build_deb.sh
        ./scripts/build_deb.sh

    - name: Upload Debian package artifact
      uses: actions/upload-artifact@v4
      with:
        name: quill-logger-release-deb
        path: ../quill-logger_*.deb 